- name: nodejs 
  include_role:
   name: common 
   tasks_from: nodejs

- name: appsetup 
  include_role: 
   name: common 
   tasks_from: app-setup

- name: systemd 
  include_role: 
   name: common 
   tasks_from: systemd 
    