- name: nodejs 
  import_role:
   name: common 
   tasks_from: nodejs

- name: appsetup 
  import_role: 
   name: common 
   tasks_from: app-setup

- name: systemd 
  import_role: 
   name: common 
   tasks_from: systemd 
    