- name: nodejs 
  import_role:
   name: common
   tasks_from: nodejs 

- name: app setup 
  import_role: 
   name: common 
   tasks_from: app-setup 
 

- name: systemd 
  import_role: 
   name: common 
   tasks_from: systemd.yaml 
    
