
- name: appsetup 
  include_role: 
    name: common 
    tasks_from: app-setup 

- name: maven 
  include_role: 
    name: common 
    tasks_from: maven 

- name: systemd 
  include_role: 
    name: common 
    tasks_from: systemd 



# - name: connect to mysql using app user
#   community.mysql.mysql_info:
#     login_user: shipping
#     login_password: RoboShop@1
#     login_host: mysql.daws84s.site
#     login_db: cities

- name: import data
  tags:
  - import
  community.mysql.mysql_db:
    name: all
    login_user: root
    login_password: RoboShop@1
    login_host: mysql.sivadevops.fun
    state: import
    target: "{{ item }}"
  loop:
  - /app/db/schema.sql
  - /app/db/app-user.sql
  - /app/db/master-data.sql

- name: Restart shipping 
  ansible.builtin.service:
    name: shipping 
    state: restarted 
